name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        
      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: latest
     
      - name: Nuget Restore 
        run: nuget restore
        
      - name: Build
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe "$Env:GITHUB_WORKSPACE\MapDemo.Wpf.sln" -p:TargetFramework=net40
           
      - uses: actions/upload-artifact@v1
        with:
          name: artifact
          path: ./MapDemo.Wpf/bin/Debug



